name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  ## Changes
  $CHANGES

categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "🧹 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "docs"

change-template: "- $TITLE (@$AUTHOR)"
no-changes-template: "- No changes"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

exclude-labels:
  - "skip-changelog"
